sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 0.12
  - 4
  - 5

before_install:
  - mkdir node_modules;

notifications:
  email:
    - wdsahadar@gmail.com

script: "npm test"